CREATE TABLE VEM_SER.PAIS(
ID_PAIS NUMBER(38,0) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY(ID_PAIS)
);

CREATE TABLE VEM_SER.ESTADO (
ID_ESTADO NUMBER(38,0) NOT NULL,
ID_PAIS NUMBER(38,0) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY(ID_ESTADO),
CONSTRAINT FK_PAIS FOREIGN KEY (ID_PAIS) REFERENCES VEM_SER.PAIS(ID_PAIS)
);

CREATE TABLE VEM_SER.CIDADE (
ID_CIDADE NUMBER(38,0) NOT NULL,
ID_ESTADO NUMBER(38,0) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY(ID_CIDADE,ID_ESTADO),
CONSTRAINT FK_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES VEM_SER.ESTADO(ID_ESTADO)
);

CREATE TABLE VEM_SER.BAIRRO (
ID_BAIRRO NUMBER(38,0) NOT NULL,
ID_CIDADE NUMBER(38,0) NOT NULL,
ID_ESTADO NUMBER(38,0) NOT NULL,
NOME VARCHAR2(50) NOT NULL,
PRIMARY KEY(ID_BAIRRO,ID_CIDADE),
CONSTRAINT FK_ESTADO_ID_CIDADE FOREIGN KEY (ID_CIDADE,ID_ESTADO) REFERENCES VEM_SER.CIDADE(ID_CIDADE,ID_ESTADO)
)

CREATE TABLE VEM_SER.ENDERECO (
ID_ENDERECO NUMBER(38,0) NOT NULL,
ID_BAIRRO NUMBER(38,0) NOT NULL,
ID_CIDADE NUMBER(38,0) NOT NULL,
LOGRADOURO VARCHAR2(255) NOT NULL,
NUMERO NUMBER(38,0) NOT NULL,
COMPLEMENTO VARCHAR2(100),
CEP CHAR(9),
PRIMARY KEY(ID_ENDERECO),
CONSTRAINT FK_BAIRRO_ID_CIDADE FOREIGN KEY (ID_BAIRRO,ID_CIDADE) REFERENCES VEM_SER.BAIRRO(ID_BAIRRO,ID_CIDADE)
)

CREATE SEQUENCE seq_pais
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_estado
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_cidade
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_bairro
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_endereco
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(seq_pais.nextval,'Brasil');

INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(seq_pais.nextval,'Portugal');

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval,1,'Sergipe' );

INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(seq_estado.nextval,2,'Estremadura Ribatejo' );

INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO , NOME)
VALUES(seq_cidade.nextval,1,'Aracaju');

INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO , NOME)
VALUES(seq_cidade.nextval,2,'Lisboa');

INSERT INTO VEM_SER.BAIRRO(ID_BAIRRO,ID_CIDADE,ID_ESTADO, NOME) VALUES(seq_bairro.nextval,1,1,'Santa Maria');

INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO,ID_CIDADE,ID_ESTADO, NOME)
VALUES(seq_bairro.nextval,2,2,'Alfama');

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO ,NUMERO ,COMPLEMENTO , CEP)
VALUES(seq_endereco.nextval,1,1,'Nourival da Silva',123,'Casa','49514-000' );

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO ,NUMERO ,COMPLEMENTO , CEP)
VALUES(seq_endereco.nextval,2,2,'abc',234,'Casa','39514-000' );

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO ,NUMERO ,COMPLEMENTO , CEP)
VALUES(seq_endereco.nextval,2,2,'Rua Itabaiana',555,'Casa','12345-000' );

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO ,NUMERO ,COMPLEMENTO , CEP)
VALUES(seq_endereco.nextval,1,1,'Rua B',444,'Casa','12345-400' );

INSERT INTO VEM_SER.ENDERECO
(ID_ENDERECO,ID_BAIRRO,ID_CIDADE,LOGRADOURO ,NUMERO ,COMPLEMENTO , CEP)
VALUES(seq_endereco.nextval,1,1,'Rua C',555,'Casa','12345-440' );

SELECT * FROM VEM_SER.PAIS ORDER BY NOME DESC;

SELECT VEM_SER.ENDERECO.LOGRADOURO , VEM_SER.ENDERECO.CEP FROM VEM_SER.ENDERECO WHERE UPPER(VEM_SER.ENDERECO.LOGRADOURO) LIKE 'A%';

SELECT VEM_SER.ENDERECO.CEP FROM VEM_SER.ENDERECO WHERE VEM_SER.ENDERECO.CEP LIKE '%0';

SELECT VEM_SER.ENDERECO.NUMERO FROM VEM_SER.ENDERECO WHERE VEM_SER.ENDERECO.NUMERO BETWEEN 1 AND 100;

SELECT VEM_SER.ENDERECO.LOGRADOURO FROM VEM_SER.ENDERECO WHERE UPPER(VEM_SER.ENDERECO.LOGRADOURO) LIKE 'RUA%' ORDER BY VEM_SER.ENDERECO.CEP DESC;

SELECT COUNT(VEM_SER.ENDERECO.ID_ENDERECO) FROM VEM_SER.ENDERECO;

SELECT VEM_SER.ENDERECO.ID_CIDADE,COUNT(VEM_SER.ENDERECO.ID_ENDERECO) FROM VEM_SER.ENDERECO GROUP BY VEM_SER.ENDERECO.ID_CIDADE;