--CREATE USER VEM_SER IDENTIFIED BY oracle;
--GRANT CONNECT TO VEM_SER;
--GRANT CONNECT, RESOURCE, DBA TO VEM_SER;
--GRANT CREATE SESSION TO VEM_SER;
--GRANT DBA TO VEM_SER;
--GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to VEM_SER;
--GRANT UNLIMITED TABLESPACE TO VEM_SER;
--GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
--GRANT CREATE TABLE TO VEM_SER;
--GRANT GLOBAL QUERY REWRITE TO VEM_SER;
--GRANT SELECT ANY TABLE TO VEM_SER;

CREATE TABLE ESTUDANTE (
id NUMBER NOT NULL,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10)  UNIQUE NOT NULL,
ativo CHAR(1),
PRIMARY KEY(id)
);

CREATE SEQUENCE seq_estudante
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Thassio', TO_DATE('09-09-1990', 'dd-mm-yyyy'), 100, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Lucas', TO_DATE('10-09-1990', 'dd-mm-yyyy'), 101, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Giovani', TO_DATE('11-09-1990', 'dd-mm-yyyy'), 102, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Rafael', TO_DATE('12-09-1990', 'dd-mm-yyyy'), 103, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Maicon', TO_DATE('13-09-1990', 'dd-mm-yyyy'), 104, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Crys', TO_DATE('14-09-1990', 'dd-mm-yyyy'), 105, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Mayra', TO_DATE('15-09-1990', 'dd-mm-yyyy'), 106, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Leonardo', TO_DATE('16-09-1990', 'dd-mm-yyyy'), 107, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Joao', TO_DATE('17-09-1990', 'dd-mm-yyyy'), 108, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(seq_estudante.nextval, 'Pedro', TO_DATE('18-09-1990', 'dd-mm-yyyy'), 109, 'N');


SELECT * FROM VEM_SER.ESTUDANTE



