-- Fazer um right outer join entre tabelas:
-- Pessoas e Contato
SELECT * FROM VEM_SER.PESSOA
	RIGHT JOIN VEM_SER.CONTATO 
	ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.CONTATO.ID_CONTATO;
	
-- Pessoa , Pessoa_X_Pessoa_Endereco e Endereco_Pessoa
SELECT * FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO
	RIGHT JOIN VEM_SER.PESSOA ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  = VEM_SER.PESSOA.ID_PESSOA
	RIGHT JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO;
	
-- Todas as tabelas (começando por pessoa)
SELECT * FROM VEM_SER.PESSOA
	RIGHT JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO 
	RIGHT JOIN VEM_SER.CONTATO ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO  = VEM_SER.CONTATO.ID_CONTATO 
	RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.CONTATO.ID_CONTATO  = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA;

-- Fazer um Outer Full Joint entre tabelas: 
-- Pessoa e Contato
SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.CONTATO ON VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.CONTATO.ID_CONTATO;
		
-- Pessoa , Pessoa_X_Pessoa_Endereco e Endereco_Pessoa
SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO
	FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO =  VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA;
	
-- Todas as tabelas ( começando por pessoa )

SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO
	FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO =  VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA
	FULL JOIN VEM_SER.CONTATO ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA = VEM_SER.CONTATO.ID_CONTATO;


SELECT VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  
FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO 
WHERE EXISTS 
	(SELECT ID_PESSOA FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO WHERE ID_ENDERECO IS NOT NULL);


