-- Fazer um right outer join entre tabelas:
-- Pessoas e Contato
SELECT * FROM VEM_SER.PESSOA
	RIGHT JOIN VEM_SER.CONTATO ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.CONTATO.ID_PESSOA;
	
-- Pessoa , Pessoa_X_Pessoa_Endereco e Endereco_Pessoa
SELECT * FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO
	RIGHT JOIN VEM_SER.PESSOA ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  = VEM_SER.PESSOA.ID_PESSOA
	RIGHT JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO;
	
-- Todas as tabelas (começando por pessoa)
SELECT * FROM VEM_SER.PESSOA
	RIGHT JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO 
	RIGHT JOIN VEM_SER.CONTATO ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.CONTATO.ID_PESSOA  
	RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA;

-- Fazer um Outer Full Joint entre tabelas: 
-- Pessoa e Contato
SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.CONTATO ON VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.CONTATO.ID_PESSOA;
		
-- Pessoa , Pessoa_X_Pessoa_Endereco e Endereco_Pessoa
SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA = VEM_SER.PESSOA.ID_PESSOA
	FULL JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO;
	
-- Todas as tabelas ( começando por pessoa )

SELECT * FROM VEM_SER.PESSOA
	FULL JOIN VEM_SER.ENDERECO_PESSOA ON VEM_SER.ENDERECO_PESSOA.ID_ENDERECO = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO
	FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA =  VEM_SER.PESSOA.ID_PESSOA
	FULL JOIN VEM_SER.CONTATO ON VEM_SER.CONTATO.ID_PESSOA = VEM_SER.PESSOA.ID_PESSOA;

-- Mostrar id pessoa , endereco , nome da pessoa e logradouro

-- Corrigido usando o UNION mostrado durante a correcao da aula 
SELECT VEM_SER.PESSOA.ID_PESSOA "ID", VEM_SER.PESSOA.NOME FROM VEM_SER.PESSOA
	UNION
	SELECT VEM_SER.ENDERECO_PESSOA.ID_ENDERECO , VEM_SER.ENDERECO_PESSOA.LOGRADOURO FROM VEM_SER.ENDERECO_PESSOA;


